name: Lint Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    strategy:
    fail-fast: false
      matrix:
        folder: [Backend, Frontend]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: ./${{ matrix.folder }}

      - name: Run ESLint
        run: |
          if [ "${{ matrix.folder }}" = "Frontend" ]; then
            npx eslint ./app
          else
            npx eslint .
          fi
        working-directory: ./${{ matrix.folder }}
